#!/usr/bin/env bash
set -euo pipefail

NAMESPACE="${1:-request-tracing-lab}"
SERVICE="${2:-request-tracing-lab}"

printf '\n== Context ==\n'
kubectl config current-context

printf '\n== Service ==\n'
kubectl get service "$SERVICE" -n "$NAMESPACE" -o wide

printf '\n== Service selector ==\n'
SELECTOR="$(kubectl get service "$SERVICE" -n "$NAMESPACE" -o jsonpath='{range $k,$v := .spec.selector}{printf "%s=%s," $k $v}{end}' | sed 's/,$//')"
if [ -z "$SELECTOR" ]; then
  echo "No selector found on service/$SERVICE"
else
  echo "$SELECTOR"
fi

printf '\n== Pods matching selector ==\n'
if [ -n "$SELECTOR" ]; then
  kubectl get pods -n "$NAMESPACE" -l "$SELECTOR" -o wide
else
  echo "Skipped because selector is empty"
fi

printf '\n== EndpointSlices ==\n'
kubectl get endpointslice -n "$NAMESPACE" -l "kubernetes.io/service-name=$SERVICE" -o wide || true

printf '\n== Service ports ==\n'
kubectl get service "$SERVICE" -n "$NAMESPACE" -o jsonpath='{range .spec.ports[*]}name={.name} port={.port} targetPort={.targetPort} protocol={.protocol}{"\n"}{end}'

printf '\n== Pod readiness and container ports ==\n'
if [ -n "$SELECTOR" ]; then
  kubectl get pods -n "$NAMESPACE" -l "$SELECTOR" -o jsonpath='{range .items[*]}pod={.metadata.name} phase={.status.phase} ready={range .status.containerStatuses[*]}{.ready}{end} ports={range .spec.containers[*].ports[*]}{.name}:{.containerPort} {end}{"\n"}{end}'
else
  echo "Skipped because selector is empty"
fi

printf '\n== Recent events ==\n'
kubectl get events -n "$NAMESPACE" --sort-by=.lastTimestamp | tail -20

printf '\nNo conclusion is generated by this script. Compare Service selector, ready Pods, EndpointSlices, Service port, targetPort, and containerPort.\n'
