{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-tracing-lab.fullname" . }}-secrets
  labels:
    {{- include "request-tracing-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLASK_SECRET_KEY: {{ .Values.secrets.FLASK_SECRET_KEY | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
{{- end }}
