apiVersion: v1
kind: ConfigMap
metadata:
  name: request-tracing-lab-config
  namespace: request-tracing-lab
data:
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5001"
  FLASK_DEBUG: "false"
  REDIS_URL: "redis://redis:6379/0"
