apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: request-tracing-lab
  namespace: request-tracing-lab
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: request-tracing-lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: request-tracing-lab
                port:
                  number: 80
